### PR TITLE
add size check script

### PR DESCRIPTION
**Pull request by rzig**
Adds a github action to prevent people from uploading unnecessarily large images.

### CODE REVIEW

**Comment by alex-m-zhang** [comment]
Can you add a quick paragraph in the README about how to aggressively squoosh things to be under 512kB?

**Comment by alex-m-zhang** [comment]
Out of curiosity, why 512kB?

**Comment by rzig** [comment]
Somewhat arbitrary, but also found that you can compress our homepage non-hero images to ~512kb (or sometimes less) and still maintain quality, so there's no need for them to be bigger

**Review by alex-m-zhang — CHANGES_REQUESTED** [review]
Can you add a quick paragraph in the README about how to aggressively squoosh things to be under 512kB?

**Review by alex-m-zhang — APPROVED** [review]
LGTM

**Pull request merged**
