### PR TITLE
Adding launch day values of tutor RS and events

### PR DESCRIPTION
**Pull request by lnguy7**

### CODE REVIEW

**Comment by lnguy7** [comment]
@rzig Please add the Zoom feature and possibly the start date, end date in events to this branch

**Comment by lnguy7** [comment]
Is it possible to have the Student Services page default to showing MIdterm 1 tab

**Comment by rzig** [comment]
The current implementation is that it defaults to the latest list that is non-empty. So removing the midterm 2 and final sessions would default it to MT1. If we don't want to do that, it's possible to rework things to set a date for when the default switches (since we don't always want to switch to MT1), would the be best?

**Comment by rzig** [comment]
I'll add zoom link but start-end ranges will be tricky and probably not worth the time

**Review by rzig — APPROVED** [review]

**Comment by lnguy7** [comment]
> 

Yeah that is perfect I think u implemented this tho

**Comment by lnguy7** [comment]
> I'll add zoom link but start-end ranges will be tricky and probably not worth the time

sg

**Comment by alex-m-zhang** [comment]
Add this: https://illinois.zoom.us/rec/share/Z8DCAE6JkgLraayhHuSL9nHU7YvEX4NtEIee3iMZ0SjtSHHVcbzOmn50r4IvUxIe.T5NG5KxRL91TcRyh

as recording link for ECE329 Review Session 1. Otherwise, approved.

**Comment by lnguy7** [comment]
> Add this: https://illinois.zoom.us/rec/share/Z8DCAE6JkgLraayhHuSL9nHU7YvEX4NtEIee3iMZ0SjtSHHVcbzOmn50r4IvUxIe.T5NG5KxRL91TcRyh
> 
> as recording link for ECE329 Review Session 1. Otherwise, approved.

Done

**Pull request merged**
